# SPDX-FileCopyrightText: The matrix-alertmanager-receiver Authors
# SPDX-License-Identifier: GPL-3.0-or-later

blank_issues_enabled: true
contact_links:
  - name: Chat Room
    url: https://matrix.to/#/#talk.metio:matrix.org
    about: Chat with the developers
